// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// b_update
Rcpp::List b_update(Rcpp::NumericMatrix x, Rcpp::NumericVector y, Rcpp::NumericVector umz, double rho, Rcpp::NumericVector beta_init);
RcppExport SEXP _SGMT_b_update(SEXP xSEXP, SEXP ySEXP, SEXP umzSEXP, SEXP rhoSEXP, SEXP beta_initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type umz(umzSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta_init(beta_initSEXP);
    rcpp_result_gen = Rcpp::wrap(b_update(x, y, umz, rho, beta_init));
    return rcpp_result_gen;
END_RCPP
}
// Lasso
arma::mat Lasso(arma::mat x, double lambda);
RcppExport SEXP _SGMT_Lasso(SEXP xSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(Lasso(x, lambda));
    return rcpp_result_gen;
END_RCPP
}
// L21
arma::mat L21(arma::mat x, double lambda);
RcppExport SEXP _SGMT_L21(SEXP xSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(L21(x, lambda));
    return rcpp_result_gen;
END_RCPP
}
// L21_w
arma::mat L21_w(arma::mat x, arma::vec lambda);
RcppExport SEXP _SGMT_L21_w(SEXP xSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(L21_w(x, lambda));
    return rcpp_result_gen;
END_RCPP
}
// gLasso
arma::mat gLasso(arma::mat x, double lambda);
RcppExport SEXP _SGMT_gLasso(SEXP xSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(gLasso(x, lambda));
    return rcpp_result_gen;
END_RCPP
}
// proxop
arma::mat proxop(arma::mat x, arma::vec groups, double lambda, double alpha);
RcppExport SEXP _SGMT_proxop(SEXP xSEXP, SEXP groupsSEXP, SEXP lambdaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(proxop(x, groups, lambda, alpha));
    return rcpp_result_gen;
END_RCPP
}
// weighted_proxop
arma::mat weighted_proxop(arma::mat x, arma::vec groups, double lambda, double alpha, arma::vec grp_weights, arma::vec ind_weights);
RcppExport SEXP _SGMT_weighted_proxop(SEXP xSEXP, SEXP groupsSEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP grp_weightsSEXP, SEXP ind_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type grp_weights(grp_weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ind_weights(ind_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_proxop(x, groups, lambda, alpha, grp_weights, ind_weights));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SGMT_b_update", (DL_FUNC) &_SGMT_b_update, 5},
    {"_SGMT_Lasso", (DL_FUNC) &_SGMT_Lasso, 2},
    {"_SGMT_L21", (DL_FUNC) &_SGMT_L21, 2},
    {"_SGMT_L21_w", (DL_FUNC) &_SGMT_L21_w, 2},
    {"_SGMT_gLasso", (DL_FUNC) &_SGMT_gLasso, 2},
    {"_SGMT_proxop", (DL_FUNC) &_SGMT_proxop, 4},
    {"_SGMT_weighted_proxop", (DL_FUNC) &_SGMT_weighted_proxop, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_SGMT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
