# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

b_update <- function(x, y, umz, rho, beta_init) {
    .Call(`_SGMT_b_update`, x, y, umz, rho, beta_init)
}

Lasso <- function(x, lambda) {
    .Call(`_SGMT_Lasso`, x, lambda)
}

L21 <- function(x, lambda) {
    .Call(`_SGMT_L21`, x, lambda)
}

L21_w <- function(x, lambda) {
    .Call(`_SGMT_L21_w`, x, lambda)
}

gLasso <- function(x, lambda) {
    .Call(`_SGMT_gLasso`, x, lambda)
}

proxop <- function(x, groups, lambda, alpha) {
    .Call(`_SGMT_proxop`, x, groups, lambda, alpha)
}

weighted_proxop <- function(x, groups, lambda, alpha, grp_weights, ind_weights) {
    .Call(`_SGMT_weighted_proxop`, x, groups, lambda, alpha, grp_weights, ind_weights)
}

